[build]
  publish = "docs"
  command = "npm --prefix frontend install && npm --prefix frontend run build && npm --prefix netlify/functions install"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  command = "npm --prefix frontend run dev"
  port = 8888
  targetPort = 3000
  autoLaunch = true

# API redirects - all functions accessible
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Admin panel redirect
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

# SPA redirect - keep last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Disable secret scanning for the Groq API key written to the chatbotKey.js file
  SECRETS_SCAN_OMIT_KEYS = "GROQ_API_KEY"

[context.production.environment]
  # Netlify Identity settings
  NETLIFY_USE_YARN = "true"

[context.deploy-preview.environment]
  # Netlify Identity settings for preview deployments
  NETLIFY_USE_YARN = "true"