[build]
  publish = "docs"
  command = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Plugin to automatically install dependencies in Netlify Functions
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[dev]
  port = 8888
  targetPort = 3000
  autoLaunch = true

# API redirects - all functions accessible
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Admin panel redirect
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

# SPA redirect - keep last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Disable secret scanning for the Groq API key written to the chatbotKey.js file
  SECRETS_SCAN_OMIT_KEYS = "GROQ_API_KEY"
  NETLIFY_BLOBS_SITE_ID = "6a528881-522e-4e8e-a178-2ac8f44c1a97"
  NETLIFY_BLOBS_TOKEN = "nfp_WHoSi6NeAginaV2j7XiofK5yMUqLxE8U3aa3"

[context.production.environment]
  # Netlify Identity settings
  NETLIFY_USE_YARN = "true"
  NETLIFY_BLOBS_SITE_ID = "6a528881-522e-4e8e-a178-2ac8f44c1a97"
  NETLIFY_BLOBS_TOKEN = "nfp_WHoSi6NeAginaV2j7XiofK5yMUqLxE8U3aa3"

[context.deploy-preview.environment]
  # Netlify Identity settings for preview deployments
  NETLIFY_USE_YARN = "true"
  NETLIFY_BLOBS_SITE_ID = "6a528881-522e-4e8e-a178-2ac8f44c1a97"
  NETLIFY_BLOBS_TOKEN = "nfp_WHoSi6NeAginaV2j7XiofK5yMUqLxE8U3aa3"